feat: view photos on reviews
restauwants/restauwants pull request #114
Opened 2024-04-02 07:40 UTC by anormananderson

Currently the signed urls associated with each image are displayed inside each post, but no functionality exists to display the actual images.

Also, for an unknown reason, sometimes no urls are returned.

2024-04-02 07:40 UTC, anormananderson commented
@callumcurtis

2024-04-05 07:34 UTC, callumcurtis requested changes

2024-04-05 07:34 UTC, callumcurtis commented on apps/nextjs/next.config.js
> +        pathname: "/restauwants_production/*",
Can "restauwants_production" (the bucket name) be an env variable instead? it's used in a bunch of other places as well.

2024-04-05 07:34 UTC, callumcurtis commented on apps/nextjs/src/app/api/photo/route.ts
> +const MAX_FILE_SIZE = 5 * 1024 * 1024; // 5 MB
this is hardcoded elsewhere in a validator - it should probably be put in a central location and reused

2024-04-05 07:34 UTC, callumcurtis commented on apps/nextjs/src/app/api/photo/route.ts
> +  const stagingBucket = storage.bucket("restauwants_staging");
these bucket names should probably be env vars eventually

2024-04-05 07:34 UTC, callumcurtis commented on apps/nextjs/src/app/api/photo/route.ts
> +    projectId: "nifty-edge-415820",
seems like an env var

2024-04-05 07:34 UTC, callumcurtis commented on apps/nextjs/src/app/api/photo/route.ts
> +  const sizeInt = z
could make this (or a part of this) a validator in the validators package and reuse it elsewhere

2024-04-05 07:34 UTC, callumcurtis commented on apps/nextjs/src/app/api/photo/route.ts
> +    "restauwants_staging",
probably should be env vars

2024-04-05 07:34 UTC, callumcurtis commented on apps/nextjs/src/app/api/photo/route.ts
> +  deleteFileIfAuthenticated(filename, "restauwants_production").catch(() =>
probably should be an env var. I'll stop mentioning these though.

2024-04-05 07:34 UTC, callumcurtis commented on apps/nextjs/src/app/api/photo/route.ts
> +  const sizeInt = z
seems like this validator could be defined once and reused above and here

2024-04-05 07:34 UTC, callumcurtis commented on apps/nextjs/src/app/api/photo/route.ts
> +function getBaseUrl() {
this looks copy and paste from the trpc file - should be extracted and shared

2024-04-05 07:34 UTC, callumcurtis commented on apps/nextjs/src/components/reviews.tsx
> +  const createPhotos = api.photo.addPhotosToReview.useMutation({
not clear what the difference between "create" and "upload" photos is

2024-04-05 07:34 UTC, callumcurtis commented on apps/nextjs/src/components/reviews.tsx
> +        console.error(error);
remove

2024-04-05 07:34 UTC, callumcurtis commented on apps/nextjs/src/components/reviews.tsx
> +        return;
does returning here work with the "submit" handling? do you need to throw an error instead?

2024-04-05 07:34 UTC, callumcurtis commented on apps/nextjs/src/components/reviews.tsx
> +      console.error(error);
remove

2024-04-05 07:34 UTC, callumcurtis commented on apps/nextjs/src/components/reviews.tsx
> +                    objectFit: "cover", // cover, contain, none
```suggestion
                    objectFit: "cover",
```

2024-04-05 07:34 UTC, callumcurtis commented on packages/api/src/router/photo.ts
> +        .lt(3 * 1024 * 1024),
should make a common validator

2024-04-05 07:34 UTC, callumcurtis commented on packages/api/src/router/photo.ts
> +  /*
remove dead code

2024-04-05 07:34 UTC, callumcurtis commented on packages/api/src/router/photo.ts
> +  ctx: {
just pass the db. See the friend router for examples.

2024-04-05 07:34 UTC, callumcurtis commented on packages/api/src/router/photo.ts
> +  const rows = [] as row[];
```suggestion
  const rows: row[] = [];
```
don't use "as", prefer colon (should search your code for other uses)

2024-04-05 07:34 UTC, callumcurtis commented on packages/api/src/router/photo.ts
> +  interface row {
you should create a Zod validator in packages/validators/src/db/index.ts instead

2024-04-05 07:34 UTC, callumcurtis commented on packages/api/src/router/photo.ts
> +function getBaseUrl() {
this always runs on the server, no? so the window will never be defined

2024-04-05 07:34 UTC, callumcurtis commented on packages/api/src/router/review.ts
> +            // TODO: Think about handling this better rather than failing silently
I think you should filter out any reviews that fail like this

2024-04-05 07:34 UTC, callumcurtis commented on packages/api/src/router/review.ts
> +            // TODO: Think about handling this better rather than failing silently
same as above - filter out reviews that fail like this

2024-04-05 07:34 UTC, callumcurtis commented on packages/api/src/router/review.ts
> +      const reviewTable = await ctx.db.insert(schema.review).values(
```suggestion
      const review = await ctx.db.insert(schema.review).values(
```
the result isn't the whole table

2024-04-05 07:34 UTC, callumcurtis commented on packages/db/src/schema/index.ts
> +  user: one(users),
doesn't link directly to user

2024-04-05 07:34 UTC, callumcurtis commented on packages/db/src/schema/index.ts
> +  review: one(review),
missing relation in the opposite direction - from review to photos

2024-04-05 07:34 UTC, callumcurtis commented on packages/validators/src/client/index.ts
> +          if (file.size === 0 || file.size > 5 * 1024 * 1024) {
file size should be a shared constant

2024-04-05 07:34 UTC, callumcurtis commented on packages/validators/src/server/external/index.ts
> +  signedUrls: z.string().array(),
could define the allowed length

2024-04-05 07:34 UTC, callumcurtis commented on packages/validators/src/server/external/index.ts
> +    .lte(3 * 1024 * 1024)
should be a shared sizes constant

2024-04-05 07:34 UTC, callumcurtis commented on packages/validators/src/server/index.ts
delete this empty file

2024-04-12 22:41 UTC, anormananderson commented
see #139

2024-04-12 22:41 UTC, closed without merging