Set up Hugo with documentation stubs
restauwants/restauwants pull request #13
Opened 2024-02-07 08:56 UTC by anormananderson

Not sure if there is a way to combine this with #12, but this is the corresponding pull request I made.

2024-02-09 20:00 UTC, anormananderson commented
@callumcurtis this should be good to go - only unknown is whether the workflow file will run correctly. If you'd rather I could open a separate repo to check first?

2024-02-09 20:02 UTC, callumcurtis commented
It's low risk so let's give it a shot first and then you can add a fix on top if something goes wrong.

2024-02-09 20:07 UTC, callumcurtis requested changes
Couple of nitpicks, otherwise LGTM. 👍

2024-02-09 20:07 UTC, callumcurtis commented on .github/workflows/hugo.yaml
> +name: Deploy Hugo site to Pages
```suggestion
name: Deploy Hugo Site to Pages
```

2024-02-09 20:07 UTC, callumcurtis commented on docs/hugo.toml
> +title = 'Restauwants Documentation'
```suggestion
title = 'RestauWants Documentation'
```

2024-02-09 20:07 UTC, callumcurtis commented on docs/hugo.toml
> +theme = "hugo-theme-relearn"
Can we change the theming to match our colors/logo?

2024-02-12 05:47 UTC, callumcurtis approved these changes

2024-02-12 05:49 UTC, callumcurtis commented
Haven't pulled to look at the theming locally but we can iterate on that as we go. For the future, a screenshot of the theme appearance in the browser would be helpful! LGTM

2024-02-12 05:49 UTC, merged