feat: Schema update branch beginning
restauwants/restauwants pull request #19
Opened 2024-02-10 03:35 UTC by Nebula5102

Beginning to update schema to use the following structure:
restaurantName -> str
reviewDescription -> str
stars -> int
price -> float 2 decimals
date -> Date
user -> Discord username
displayName -> str

2024-02-10 09:12 UTC, Nebula5102 commented
Updated database schema. Started to make changes to posts and form for making posts, but did not finish any features. Create post button on review page is currently not working. The new schema looks like this:
```
  id: int("id").autoincrement().primaryKey(),
  restaurantName: varchar("restaurantName", { length: 256 }),
  reviewText: varchar("reviewText", { length: 256 }),
  stars: int("stars").default(5),
  price: float("price"),
  date: datetime("date"),
  displayName: text("displayName"),
  createdAt: timestamp("created_at")
    .default(sql`CURRENT_TIMESTAMP`)
    .notNull(),
  updatedAt: timestamp("updatedAt").onUpdateNow(),
  ```

2024-02-14 00:04 UTC, Nebula5102 commented
Schema is fully updated and usable. Ready to be merged to main for milestone 1. Currently we are missing the functionality of a authorized users being able to make a post and have the username field in the schema be updated to that users username. We will need to fix this in the future for sorting of posts by user etc. Immediate todos: 
Update styling of review page
implement a way to update fields of post using user input
Update styling of feed page
Update styling of posts

2024-02-14 00:29 UTC, callumcurtis commented
Resolves #18

2024-02-14 01:01 UTC, callumcurtis requested changes
I think it's important to fix the UI issues for this milestone 1 but the security and schema issues can be resolved after M1, included them in the review so that someone can refer to them later when working on this code later

2024-02-14 05:37 UTC, Nebula5102 commented on apps/nextjs/src/app/_components/posts.tsx
> +        <div className=""></div>
removed, it is not needed

2024-02-14 05:38 UTC, Nebula5102 commented on apps/nextjs/src/app/_components/posts.tsx
> +          <p className="text-base text-black">
implemented suggestion

2024-02-14 05:40 UTC, Nebula5102 commented on apps/nextjs/src/app/_components/posts.tsx
> +      <div className="relative flex w-full flex-col content-center gap-4">
implemented suggestion

2024-02-16 04:20 UTC, closed without merging