Feat/prof page improvements
restauwants/restauwants pull request #64
Opened 2024-02-26 00:27 UTC by camrohwer

Logout popup modal dialog for confirmation

2024-02-27 01:20 UTC, anormananderson commented on apps/nextjs/src/app/profile/page.tsx
> +                    Are you absolutely sure you want to Log Out?
```suggestion
                    Are you absolutely sure you want to log out?
```

2024-02-27 01:23 UTC, anormananderson reviewed
Are we worried at all about the discrepancy between functions named according "signing" in and out, whereas our dialogs refer to "logging" in and out?

(I can change this "Comment" into an "Approve," but I assumed you were looking for a review from someone who has previously touched the auth code.)

2024-02-29 20:58 UTC, callumcurtis requested changes
Looks good. Small suggestion about using an icon.

2024-02-29 20:58 UTC, callumcurtis commented on apps/nextjs/src/app/profile/page.tsx
> +              <AlertDialogTrigger>Log Out</AlertDialogTrigger>
I'd like to see a logout icon ([example](https://www.google.com/search?sca_esv=6459c9e3b5d5a0f2&q=logout+icon&tbm=isch&source=lnms&sa=X&ved=2ahUKEwjCm8aTt9GEAxXCHTQIHTrKDCoQ0pQJegQIEBAB&biw=1440&bih=2399&dpr=1#imgrc=tlNev458ccsWWM), corresponds to "Exit" in Radix Icons) tried instead

2024-02-29 20:58 UTC, callumcurtis commented on packages/ui/src/button.tsx
> +        transparent: "bg-transparent text-primary-foreground",
If you go with the icon approach you could remove this as it wouldn't be needed

2024-03-07 21:44 UTC, closed without merging